### ISSUE TITLE
Erro pedido acima de R$ 1000,00 no cartão de crédito

### ISSUE THREAD

**Issue by G0dzzilla** [opencart-extension/PagSeguro-Checkout-Transparente#11]
Opencart 2.1.0.2  com PagSeguro-Checkout Transparente 1.3.5

Compras acima de R$ 1.000,00 retorna a seguinte mensagem ao tentar finalizar o pedido com o cartão de crédito selecionado:
item amount invalid pattern: 1,025.00. Must fit the patern: \d+.\d{2}

ao tentar finalizar o pedido com o cartão de crédito selecionado retorna o seguinte:
invalid creditcard data

As mensagens de erro estão em inglês (é possível traduzir em algum arquivo?).
Abaixo a mensagem caso a data da validade do cartão esteja incorreta:
invalid date format

**Comment by valdeir2000** [comment]
Correção:

https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/commit/5a0cc32ac755dce916202e8fede71c49ebbcb0ef
