### ISSUE TITLE
Boleto não adiciona desconto no pagamento

### ISSUE THREAD

**Issue by jovtrc** [opencart-extension/PagSeguro-Checkout-Transparente#13]
Boa tarde!

Não estou conseguindo fazer funcionar o desconto para pagamentos no boleto.
Estou tentando fazer 20% de desconto, mas não vai.

Estou usando a versão 1.3.6 no Opencart 2.2.0, tentei usar uma versão mais recente, mas pelo que parece, elas são para as versões mais recentes do Opencart.

Imagens:

Quando seleciono boleto:
![img1](https://user-images.githubusercontent.com/34073572/33339715-32f87ce8-d461-11e7-99c0-12f09d2b69ee.PNG)

Quando aparece o boleto:
![img2](https://user-images.githubusercontent.com/34073572/33339724-3b55558c-d461-11e7-9d52-4da203d31475.PNG)

Dentro do admin, vendo o pedido:
![img3](https://user-images.githubusercontent.com/34073572/33339735-43ba3030-d461-11e7-86ff-7863e5ac8c5b.PNG)

Indo na aba Debug nas configurações do módulo, só vejo isso:
```
2017-11-28 19:22:59 - Array 
( 
[data] => 
) 

2017-11-28 19:22:59 - Array 
( 
```

Será que é possível corrigir esse problema?

**Comment by valdeir2000** [comment]
@jovtrc Abra o arquivo https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/blob/1.3.5/upload/catalog/controller/extension/payment/pagseguro_boleto.php#L156

Adicione o seguinte código ```php
file_put_contents("pag.log", json_encode($data));
```

Poste o resultado do arquivo aqui.

**Comment by valdeir2000** [comment]
https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/commit/a38de46534359225d923f994ef1069a9dcc3666b

**Comment by jovtrc** [comment]
Olá!

Valdeir, me desculpa a demora.

Modifiquei os arquivos, e mesmo assim não foi resolvido.

Coloquei aquela linha do log também, apareceu isso nele:

```
2017-12-14 13:21:36 - Array
(
    [data] => 
)

2017-12-14 13:21:36 - Array
(
    [response] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><transaction><date>2017-12-14T11:21:34.000-02:00</date><code>907C6197-96D3-4EAB-8F28-C4E28667521B</code><reference>Pedido #75</reference><type>1</type><status>1</status><lastEventDate>2017-12-14T11:21:36.000-02:00</lastEventDate><paymentMethod><type>2</type><code>202</code></paymentMethod><paymentLink>https://pagseguro.uol.com.br/checkout/payment/booklet/print.jhtml?c=b9594197971f70a3051968437776f3e1b1983ecf1a34e7b68e7f68ed7cd6714221c58e2c50fb2598</paymentLink><grossAmount>551.25</grossAmount><discountAmount>0.00</discountAmount><feeAmount>22.39</feeAmount><netAmount>528.86</netAmount><extraAmount>0.00</extraAmount><installmentCount>1</installmentCount><itemCount>1</itemCount><items><item><id>55</id><description>Corrente Grumet Elo Longo Ouro Amarelo 18K 40 cm | B306540</description><quantity>1</quantity><amount>551.25</amount></item></items><sender><name>João Carvalho</name><email>joaoccc@gmail.com</email><phone><areaCode>11</areaCode><number>984779546</number></phone></sender><shipping><address><street>Rua ABC</street><number>500</number><complement></complement><district>Jardim XYZ (Zona Norte)</district><city>São Paulo</city><state>SP</state><country>BRA</country><postalCode>02228100</postalCode></address><type>1</type><cost>0.00</cost></shipping></transaction>
)
```
