### ISSUE TITLE
Valor das parcelas incorreto

### ISSUE THREAD

**Issue by marceloamp2** [opencart-extension/PagSeguro-Checkout-Transparente#14]
Olá,

No total de compras com o frete está dando por exemplo R$ 251,00 e nas parcelas do cartão de crédito está 3 X 88,72 e com isso ocorre o erro de valor das parcelas incorreto.

Marcelo

**Comment by vmfadvancedwind** [comment]
Pra adicionar outro detalhe, ele não está considerando valores de impostos no campo itemAmount1 e isso faz com que installmentValue nunca fique certo e o pagseguro sempre rejeite. Pode ser que o seu caso seja derivado do mesmo problema, se tiver configurações de impostos.

**Comment by marceloamp2** [comment]
Em impostos foi excluído tudo. Mas esse valor das parcelas não é o seu
módulo que faz a soma? Porque creio que nem chega a enviar para o PagSeguro.

Marcelo

Em 8 de dezembro de 2017 16:54, vmfadvancedwind <notifications@github.com>
escreveu:

**Comment by marceloamp2** [comment]
No meu caso a soma das parcelas não está correta, nem chega a enviar. Se envio ocorre o mesmo erro.

**Comment by valdeir2000** [comment]
@marceloamp2 e @vmfadvancedwind acabei de lançar uma modificação.

Segue alterações que fiz:
https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/commit/a38de46534359225d923f994ef1069a9dcc3666b

https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/commit/b98385386710ab4ab45988da20bf626426032637

Se possível, deem um feedback.

**Comment by marceloamp2** [comment]
Eu consegui resolver o problema adicionando o = na linha abaixo no arquivo pagseguro_cartao.twig

151  {% if max_parcelas_sem_juros|length >= 1 %}

Após isso consegui realizar o pagamento por cartão tanto em sandbox quanto em produção. Outro problema que ocorreu é que o pedido não está aparecendo no histórico de pedidos do opencart porque está sendo marcado como "Pedido abandonado" sendo necessário escolher esse filtro para ele aparecer.

**Comment by vmfadvancedwind** [comment]
@valdeir2000 Ainda não resolve o problema completamente. Com a sua alteração, ele continua dando o mesmo erro de antes, mas agora é por causa que ExtraAmount já tem o frete, e depois ele soma com ShippingCost e aí novamente o valor das parcelas não bate com o valor do produto.

Uma correção temporária que confirma isso é colocar 

$data['shippingCost'] = "0.00"; 

Antes de enviar. Com essa mudança, ele funciona. Embora imagino que o mais correto seria o frete vir separado do extra amount

**Comment by andressacb** [comment]
Oi pessoal, estou com problema nessa parte também.
Ele fecha o pedido com o valor correto, mas quando vai para o pagseguro vai com o valor errado.
Alterei essa linha e fechou com o valor correto.
$data["extraAmount"] = $order_info["total"] - $this->cart->getSubTotal();
para
$data["extraAmount"] = 0;

mas ai se coloco um cupom de desconto, vai errado para o pagseguro.

**Comment by valdeir2000** [comment]
@andressacb corrigir esse problema.

No OC 3.x, quando uso um cupom de desconto com frete grátis, ele acaba aparecendo no totals como se houvesse uma cobrança. Confuso.

Esse problema resolvi dessa forma.

```
/* Tipo e Valor do Frete */
if ($this->cart->hasShipping() && !$shipping_free){
	$data['shippingType'] = $this->model_extension_payment_pagseguro->getShippingType();
		
	$data['shippingCost'] = number_format($this->session->data['shipping_method']['cost'], 2, '.', '');
            
        $data["extraAmount"] -= $this->session->data['shipping_method']['cost']; //Correção
}
```

**Comment by vmfadvancedwind** [comment]
@valdeir2000 Precisa colocar number_format nesse extraAmount depois da correção ou pode dar problema do formato do pagseguro. Dá pra simplesmente mover onde estava algumas linhas acima 
`$data['extraAmount'] = number_format($data['extraAmount'], 2, '.', '');`
Pra depois dessa correção

**Comment by 3-dimensional** [comment]
Alguma solução definitiva pra esse problema já existe?
