### ISSUE TITLE
Sessão é encerrada após realizar compra

### ISSUE THREAD

**Issue by vmfadvancedwind** [opencart-extension/PagSeguro-Checkout-Transparente#15]
Após realizar uma compra com qualquer uma das opções, a sessão é encerrada. Estou usando como base o sandbox do pagseguro.

Se realizar uma compra com boleto, ele funciona normalmente até a tela que você seleciona se pagou ou não pro sandbox do pagseguro. Ao fechar essa janela, ele causa esse erro

<b>Notice</b>: Undefined index: order_id in <b>/catalog/controller/extension/payment/pagseguro_boleto.php</b> on line <b>202</b>

(código da linha: 

`$this->model_checkout_order->addOrderHistory($this->session->data['order_id'], $status);`

) 

E atualiza a tela, com o usuário **deslogado**. O que aliás é a causa do indice não ter sido encontrado, ali ele já não tem mais os dados de sessão. Isso ocorrendo, a venda não é finalizada (ela fica como **Pedido Abandonado**), e se relogar com o usuário os itens permanecem no carrinho. O mesmo erro também ocorre nas outras formas de pagamento, na mesma execução de código 

Conteúdo da aba debug das configurações da extensão:

`2017-12-12 17:20:54 - Array ( [data] => ) 2017-12-12 17:20:54 - Array ( [response] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><transaction><date>2017-12-12T15:21:24.000-02:00</date><code>CB7A2EA1-6C88-44F2-BEDB-94F0C0462ADF</code><reference>Pedido #22</reference><type>1</type><status>1</status><lastEventDate>2017-12-12T15:21:25.000-02:00</lastEventDate><paymentMethod><type>2</type><code>202</code></paymentMethod><paymentLink>https://sandbox.pagseguro.uol.com.br/checkout/payment/booklet/print.jhtml?c=e24f45454f55a9c41ffbe71a8c64500920037e101e10c194eacffa54d0caa2fd3f969bc3c3485168</paymentLink><grossAmount>358.22</grossAmount><discountAmount>0.00</discountAmount><feeAmount>14.69</feeAmount><netAmount>343.53</netAmount><extraAmount>69.22</extraAmount><installmentCount>1</installmentCount><itemCount>1</itemCount><items><item><id>50</id><description>Micofenolato De Mofetila | 500mg - 50 comprimidos</description><quantity>1</quantity><amount>289.00</amount></item></items><sender><name>Name</name><email>email@sandbox.pagseguro.com.br</email><phone><areaCode>12</areaCode><number>1212121</number></phone><documents><document><type>CPF</type><value>removido</value></document></documents></sender><shipping><address><street>Rua Teste</street><number>121</number><complement></complement><district>Teste</district><city>Barueri</city><state>SP</state><country>BRA</country><postalCode>removido</postalCode></address><type>2</type><cost>0.00</cost></shipping></transaction> )`

**Comment by valdeir2000** [comment]
@vmfadvancedwind Recentemente fiz esse tutorial que você auxiliar.

https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/wiki/%5BComo-Corrigir%5D-Undefined-index:-order_id

**Comment by vmfadvancedwind** [comment]
@valdeir2000 O problema é que fazendo isso a ordem até é inserida, mas a perda da sessão permanece, o que é um incoveniente para o usuário final. Estou tentando descobrir onde exatamente isso acontece, até para determinar se é um problema de configuração do servidor, por exemplo (embora uma forma de pagamento padrão do opencart como pagamento na entrega funciona normal).

**Comment by vmfadvancedwind** [comment]
Ele perde a sessão nessa linha da função transition. Ainda não descobri a razão. 

`$this->session->data['pagseguro_response'] = $response;`

**Comment by vmfadvancedwind** [comment]
@valdeir2000 
Problema foi corrigido em meu servidor trocando $response por $xml (que contém um simplexmlobject e não um xml em si). Se tentar colocar uma string xml puro (que se encontra na variável response), a sessão é destruída. Não faço a menor ideia da razão. Fica assim no final, precisa ser feito nas três formas de pagamento. 

`$this->session->data['pagseguro_response'] = $xml;`

Provavelmente precisarei alterar o código de outros locais usando essa variável esperando o formato antigo.

**Comment by valdeir2000** [comment]
Acabei removendo esse trecho.

**Comment by vmfadvancedwind** [comment]
Sim, eu também removi depois, não usa em lugar nenhum
