### ISSUE TITLE
Pedidos abandonados / pagamento não atualizando status

### ISSUE THREAD

**Issue by vmfadvancedwind** [opencart-extension/PagSeguro-Checkout-Transparente#16]
No arquivo 

https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/blob/master/upload/catalog/controller/extension/payment/pagseguro.php

Todos as linhas $this->config->get("pagseguro_"); estão errados. O correto deveria ser $this->config->get("payment_pagseguro_"). Isso explica problemas relatados como pedidos ficando com o status abandonado, sem essa correção, o $status fica vazio nessa linha, causando o problema. 

https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/blob/master/upload/catalog/controller/extension/payment/pagseguro.php#L49

Todos os outros arquivos acessando config parecem estar corretos, menos esse.

**Comment by valdeir2000** [comment]
Valeu pela observação @vmfadvancedwind . Problemas com essa migração do OC para 3.x.
