### ISSUE TITLE
Token de sessão inválido.

### ISSUE THREAD

**Issue by jefersonmatana** [opencart-extension/PagSeguro-Checkout-Transparente#17]
Estou utilizando Opencart 2.3.2. Utilizava a versão 1.3.6 e tentei atualizar para a mais recente 1.4.1, porém toda vez que tento configurar as opções do módulo no admin, ao salvar, o meu usuário é deslogado e aparece a mensagem:  O token de sessão é inválido. Tente acessar novamente.
Talvez tenha algum processo de atualização que eu deva realizar? Ou porque isto está acontecendo?

**Comment by valdeir2000** [comment]
A versão 1.4.x não é compatível com a versão 2.x do OC.

**Comment by jefersonmatana** [comment]
Posso usar a versão 1.3.6 que encontro no site do opencart? Estava atualizando para corrigir o bug com a notificação automática que não está funcionando. É possível corrigir para a versão 2.x do opencart?
Obrigado Valdeir
