### ISSUE TITLE
Existe a possibilidade de capturar e traduzir as mensagens de resposta de erros no cliente?

### ISSUE THREAD

**Issue by rainyer** [opencart-extension/PagSeguro-Checkout-Transparente#19]

**Comment by valdeir2000** [comment]
Essa modificação foi feita na nova versão do módulo. Para OC 3.x

https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/commit/ab1c304e39f0c79a6659417c32e9a84cf19c03b1#diff-46ed0d15b4e73d10f3e4960a2b092115
