### ISSUE TITLE
boleto sem aviso de acrescentar 1 real ...

### ISSUE THREAD

**Issue by marcelowu** [opencart-extension/PagSeguro-Checkout-Transparente#23]
boleto sem aviso de acrescentar 1 real ...

**Comment by wachs** [comment]
Esse problema não é no módulo. Você pode desabilitar essa opção na conta do pagseguro e arcar com o valor do boleto.
Se não é só ajustar na tradução e incluir uma frase informativa.

**Comment by marcelowu** [comment]
valeu pela dica
