### ISSUE TITLE
erro na informação da data com pagamento através do cartão

### ISSUE THREAD

**Issue by roglads** [opencart-extension/PagSeguro-Checkout-Transparente#26]
Quando a opção de pagamento de cartão é selecionada o sistema mostra um erro de informação de data impossibilitando a concretização da venda, seja débito ou crédito.

**Comment by valdeir2000** [comment]
@roglads poderia detalhar ou postar um __print__ do erro?

**Comment by roglads** [comment]
![error date format](https://user-images.githubusercontent.com/45758247/49795311-d0489a80-fd20-11e8-9f57-4edc893b94d8.jpeg)

Bom dia Valdeir, segue o print screen do erro da date: invalid date format, aparece em vermelho no canto superior esquerdo.

**Comment by valdeir2000** [comment]
Tentei testar, mas o módulo não está habilitado.

**Comment by vipartweb** [comment]
Ola, começou a ocorrer o mesmo problema pra mim, o módulo esta habilitado, ainda buscando uma solução para o problema da invalid date format.

**Comment by omegasites** [comment]
Olá, também estou com o mesmo problema ao tentar efetuar o pagamento via cartão. Está dando "formato de data inválido". Poderia me ajudar? Opencart 3.0.3.2
