### ISSUE TITLE
Compra por 1 clique

### ISSUE THREAD

**Issue by andrelacomski** [opencart-extension/PagSeguro-Checkout-Transparente#30]
Estou testando e ele não salva os dados do cartão para compras futuras, sabe como proceder? 
Mesmo que a compra não seja aprovada ela salva o cartão?

**Comment by valdeir2000** [comment]
Olá,

O módulo não salva os dados dos cartões, pois estes são sensíveis e —
infelizmente — muitas lojas não seguem os padrões de segurança.

Caso deseje implementar essa opção, recomendar-te-ei três *links*:
https://www.pcisecuritystandards.org/
https://www.pcisecuritystandards.org/pdfs/Small_Merchant_Guide_to_Safe_Payments.pdf
https://www.pcisecuritystandards.org/pdfs/pci_fs_data_storage.pdf


*VALDEIR S.*
Analista de Sistemas | Dev
site:  www.valdeirsantana.com.br
email:  valdeir.naval@gmail.com
skype:  valdeir2000

<https://github.com/valdeirpsr>  <https://t.me/valdeirpsr>
<https://medium.com/@valdeirpsr>


Em sex, 6 de set de 2019 às 14:12, Andre Tohouca Lacomski <
notifications@github.com> escreveu:
