### ISSUE TITLE
Erro de javascrip quando faz pagamento.

### ISSUE THREAD

**Issue by RafaelScharf** [opencart-extension/PagSeguro-Checkout-Transparente#31]
Veja a imagem abaixo:
![image](https://user-images.githubusercontent.com/42837920/75093867-9437d900-5564-11ea-80cb-fd56e9bd8fc8.png)

esse é o erro que recebo quando tento pagar uma compra!
Veja o meu console:
![image](https://user-images.githubusercontent.com/42837920/75093898-d4975700-5564-11ea-9948-6830615bdbd7.png)

Esse é minhas requisições no momento:
![image](https://user-images.githubusercontent.com/42837920/75093933-1cb67980-5565-11ea-85fe-36f10ed87272.png)

Alguem pode me ajudar?

**Comment by valdeir2000** [comment]
Olá,

Segue link para correção:
https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/wiki/%5BComo-Corrigir%5D-Erro-ao-carregar-javascript
.

Em sáb, 22 de fev de 2020 11:19, Rafael Klein Scharf <
notifications@github.com> escreveu:

**Comment by RafaelScharf** [comment]
O link me leva pra criar uma nova pagina na wiki, poderia verificar por favor?

**Comment by valdeir2000** [comment]
https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/wiki

Em qua, 26 de fev de 2020 12:49, Rafael Klein Scharf <
notifications@github.com> escreveu:

**Comment by RafaelScharf** [comment]
Obrigado, irei tentar.
