### ISSUE TITLE
O valor minimo para compras não funciona

### ISSUE THREAD

**Issue by here-biaa** [opencart-extension/PagSeguro-Checkout-Transparente#33]
Preciso que o valor minimo para compras via cartao de credito seja de R$20,00

**Comment by HaftasArden** [comment]
É possível configurar essa opção no painel de configuração do módulo.

**Comment by opencart-extension** [comment]
É possível configurar essa opção no painel de configuração do módulo.

**Comment by here-biaa** [comment]
Certo, eu coloquei no módulo que o valor minimo para compras via cartão de crédito seria de R$100,00 no entanto ao ir para o checkout com o produto no valor total de R$80,00 ele me dá a opção de parcelar em até 12x. Pode me ajudar por gentileza?
