### ISSUE TITLE
Parcelamento minimo Checkout

### ISSUE THREAD

**Issue by here-biaa** [opencart-extension/PagSeguro-Checkout-Transparente#34]
Coloquei no módulo que o valor minimo para compras via cartão de crédito seria de R$100,00, no entanto ao ir para o checkout com o produto no valor total de R$80,00 ele me dá a opção de parcelar em até 12x. O certo seria oferecer apenas a opção de parcela em 1x.
Alguém pode me ajudar por gentileza?

**Comment by opencart-extension** [comment]
Olá!

O valor mínimo é para a forma de pagamento ser exibido e não referente ao valor da parcela mínima.
