### ISSUE TITLE
installment invalid value (arredondamento do valor)

### ISSUE THREAD

**Issue by giovannefc** [opencart-extension/PagSeguro-Checkout-Transparente#41]
deu erro, acabei postando denovo. achei que tinha perdido tudo.

**Comment by valdeir2000** [comment]
https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/issues/42

**Comment by valdeir2000** [comment]
Olá, tudo bem?

Poderia me tirar algumas dúvidas?

 - Você está usando múltiplas moedas? Qual o valor os valores delas?
 - Qual taxa (juros %) você está usando?
 - Qual a quantidade de parcelas que ocorre o erro?
 - Poderia extrair os dados referente ao pedido com erro das tabelas: *oc_order_product* e *oc_order_total*?
 - Poderia compartilhar todo XML enviado e recebido pela API (Antes, suprimir as informações do cliente e token)?

**Comment by giovannefc** [comment]
Boa noite.
Desculpe pela confusão, na hora de postar perdi tudo, depois vi que tinha postado, virou uma salada! rsrs

Vamos lá.
1. Não, está padrão Real.
2. Não tem nada configurado de taxa.
3. Em 1 parcela mesmo.
4. Em oc_order_product o valor de **price** e **total** estão iguais: **26.95**. Em oc_order_total, o registro do order_id correspondente, está correto tb `code: total` -> `value: 26.95` e `code: shipping` -> `value: 5.00`
5. **request**:
`<?xml version="1.0" encoding="utf-8"?> <payment><mode>default</mode><method>creditcard</method><sender><name>Giovanne Castro</name><email>xxxxxxxx@sandbox.pagseguro.com.br</email><hash>xxxxx</hash><phone><areaCode>19</areaCode><number>9999999</number></phone><documents><document><type>CPF</type><value>22222222222</value></document></documents></sender><currency>BRL</currency><notificationURL>https://www.sitecom.br/index.php?route=extension/payment/pagseguro/callback&amp;order_id=8&amp;token=xxxx</notificationURL><items><item><id>ID50_K0</id><description>Leite Ninho Fases +1 800g  ::  800g</description><amount>27.00</amount><quantity>1</quantity></item></items><extraAmount>0.00</extraAmount><shipping><type>3</type><cost>5.00</cost><addressRequired>true</addressRequired><address><street>Avenida Nelsia, 200</street><number>105</number><district>Parque Prado</district><city>Campinas</city><state>SP</state><country>BRA</country><postalCode>13042104</postalCode></address></shipping><creditCard><token>tokenxxxxxx</token><installment><quantity>1</quantity><value>31.95</value><noInterestInstallmentQuantity>3</noInterestInstallmentQuantity></installment><holder><name>Teste teste</name><birthDate>08/09/1986</birthDate><documents><document><type>CPF</type><value>22222222222</value></document></documents><phone><areaCode>19</areaCode><number>98888888</number></phone></holder><billingAddress><street>Avenida Nelsia, 200</street><number>200</number><district>Parque Prado</district><city>Campinas</city><state>SP</state><country>BRA</country><postalCode>13000000</postalCode></billingAddress></creditCard></payment>`
**response**:
`<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53041</code><message>installment value invalid value: 31.95</message></error></errors>`

Uma coisa que me esqueci de mencionar é que depois eu alterei o valor do produto para R$ 28,00 redondo e fiz a compra novamente com o frete de R$ 5,00 e tudo mais, totalizando R$ 33,00. Daí deu certo! Sem erro. Verifiquei os logs os valores estavam corretos.

Obrigado pela breve resposta.

**Comment by valdeir2000** [comment]
Fiz um teste com os mesmos valores (produto + frete) e ocorreu tudo OK.

**Comment by giovannefc** [comment]
Já achei o problema.
Estou usando a versão do release 2.0...
Que não tem a modificação/correção onde está o problema de aredondamento:
https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/commit/7bcd62f4689056c3113ab239d1943c753203f80a
Vou atualizar aqui pra última snapshot...

**Comment by lucaslealdev** [comment]
Solicito o fechamento da issue por ter sido resolvido no commit 7bcd62f
