### ISSUE TITLE
Qual a versao que a extensao suporta?

### ISSUE THREAD

**Issue by rodrigomanara** [opencart-extension/PagSeguro-Checkout-Transparente#45]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Por favor, utilize nosso [canal de atendimento](https://valdeirpsr.atlassian.net/servicedesk/customer/portal/3) ou envie um e-mail para [contato@valdeir.dev](mailto:contato@valdeir.dev)

Obrigado!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by opencart-extension** [comment]
OC 3+
