### ISSUE TITLE
Erro pedido acima de R$ 1000,00

### ISSUE THREAD

**Issue by vynnus** [opencart-extension/PagSeguro-Checkout-Transparente#5]
compras acima de R$ 1.000,00 retorna a seguinte mensagem ao tentar finalizar o pedido com o boleto selecionado:
`item amount invalid pattern: 1,025.00. Must fit the patern: \d+.\d{2}`

ao tentar finalizar o pedido com o cartão de crédito selecionado retorna o seguinte:
`invalid creditcard data`

As mensagens de erro estão em inglês (é possível traduzir em algum arquivo?).
Abaixo a mensagem caso a data da validade do cartão esteja incorreta:
`invalid date format`

**Comment by valdeir2000** [comment]
Corrigido.

Irei adicionar tradução para os erros em breve.
