### ISSUE TITLE
Botão BAIXAR BOLETO produz um arquivo .PDF que não é válido.

### ISSUE THREAD

**Issue by MarcosLealDev** [opencart-extension/PagSeguro-Checkout-Transparente#53]
# 🐞 relatório da falha

### Parte afetada

 - [ ] Admin
 - [X] Módulo de Boleto
 - [ ] Módulo de Cartão de Crédito
 - [ ] Módulo de Cartão de Débito
 - [ ] Módulo de Desconto
 - [ ] Módulo de Taxa
 - [ ] Outro: **informe-nos aqui**

### Este comportamento funcionava na versão anterior?
Esta função não existia na versão anterior que eu me lembre. Ou existia a funcionava corretamente.

### Descrição

No Checkout, o botão BAIXAR BOLETO produz um arquivo .PDF que não é válido.

Inspecionando melhor, o arquivo produzido é um .PNG.

## 🔬 Passo a passo para reprodução do erro

1. Faça compra e vá ao Checkout
2. Após confirmar os dados, selecione a forma de pagamento como Boleto
3. Confirme o Pedido
4. Você vai ter 2 opções para visualizar ou baixar o boleto.
5. Clicando em Baixar, um arquivo será gerado e o download inicia.
6. Tentando abrir o arquivo .PDF gerado, retorna o erro.

## 🌍  Seu ambiente

| Ferramenta                    | Versão |
| ----------------------------- | :----: |
| OpenCart                      |     3.0.3.3 Brasil 1.5.0   |
| MySQL                         |    14.14    |
| WebServer (Apache, Nginx etc) |   Apache php7.3-fpm   |

**Outras informações relevantes?**

Renomeando o arquivo .PDF para .PNG é possível abrir sem problemas.

**Comment by valdeir2000** [comment]
Olá, Marcos. 
Obrigado pelo feedback.

A correção foi feita, deve sair na versão 2.1

abc7504e556e7c6ad253b19c29b13ba40683ab3d
