### ISSUE TITLE
Data de Nascimento formatada como mm/dd/yyyy

### ISSUE THREAD

**Issue by MarcosLealDev** [opencart-extension/PagSeguro-Checkout-Transparente#54]
# 🐞 relatório da falha

### Parte afetada

 - [ ] Admin
 - [ ] Módulo de Boleto
 - [X] Módulo de Cartão de Crédito
 - [ ] Módulo de Cartão de Débito
 - [ ] Módulo de Desconto
 - [ ] Módulo de Taxa
 - [ ] Outro: **informe-nos aqui**

### Este comportamento funcionava na versão anterior?

Este requerimento de Data de Nascimento não existia na versão anterior. O valor era lido do cadastro do cliente.

### Descrição

Ao selecionar cartão de crédito, a Data de Nascimento não é lida do cadastro do cliente. 
O formato vem como o Norte Americano mm/dd/yyy e não dd/mm/yyy. 
Clicando no Date Picker, mostra os dias da semana em Inglês
![CC_Date_Format](https://user-images.githubusercontent.com/14096346/108015485-5ede9380-6fde-11eb-891c-8438dd486753.png)

## 🔬 Passo a passo para reprodução do erro

1. Ao fazer a compra na loja, finalize ...
2. Escolha pagamento com Cartão de Crédito
3. Verifique o requerimento da Data de Nascimento
4. Clique no botão Date Picker e verique que tudo está em inglês. 

## 🌍  Seu ambiente

| Ferramenta                    | Versão |
| ----------------------------- | :----: |
| OpenCart                      |     3.0.3   |
| MySQL                         |    14.14    |
| WebServer (Apache, Nginx etc) |    apache2 php7.3-fpm    |

**Outras informações relevantes?**

Foi testado no Chrome numa máquina com Windows 10 em inglês.  
O Opencart está todo em português e usando a versão 1.5.0 do Opencart Brasil.

**Comment by valdeir2000** [comment]
Olá, Marcos!
O campo segue a linguagem definida no navegador. É possível adicionar outro modelo de _datepicker_, porém seria alguns _kilobytes_ a mais (talvez não seja um problema) ou adicionar `<select>` para o preenchimento.

![image](https://user-images.githubusercontent.com/606481/108575446-0a4a5980-72f9-11eb-96ee-a104c91bfc1a.png)

Quando ao preenchido vindo do cadastro, irei dar realizar a modificação necessária.
