### ISSUE TITLE
Pagmento via Cartão gerou o erro "no interest installment quantity out of range 1."

### ISSUE THREAD

**Issue by MarcosLealDev** [opencart-extension/PagSeguro-Checkout-Transparente#57]
# 🐞 relatório da falha

### Parte afetada

 - [ ] Admin
 - [ ] Módulo de Boleto
 - [X] Módulo de Cartão de Crédito
 - [ ] Módulo de Cartão de Débito
 - [ ] Módulo de Desconto
 - [ ] Módulo de Taxa
 - [ ] Outro: **informe-nos aqui**

### Descrição
Quando o cliente seleciona a opção de cartão de crédito e com todos os valores preenchidos, a mensagem de erro aparece:
"no interest installment quantity out of range 1. The value must be greater than1".

![PagSeguro_Erro_1](https://user-images.githubusercontent.com/14096346/127044397-b5fc093a-7a10-412f-9af3-8734aa39abc7.jpg)
![PagSeguro_Erro_2](https://user-images.githubusercontent.com/14096346/127044416-380cc570-78d0-4f99-b388-399719d69da2.jpg)

## 🌍  Seu ambiente

| Ferramenta                    | Versão |
| ----------------------------- | :----: |
| OpenCart                      |   3.0.3.3     |

**Módulos do PHP:**
<pre><code>
7.3
</code></pre>

**Comment by MarcosLealDev** [comment]
Informações dentro do Debug Warning - Request:
```
<installment><quantity>5</quantity><value>280.30</value><noInterestInstallmentQuantity>1</noInterestInstallmentQuantity></installment>
```
E no Response:
```
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53148</code><message>no interest installment quantity out of range: 1. The value must be greater than 1.</message></error></errors>
```

**Comment by valdeir2000** [comment]
Olá, tudo bem?

Poderia adicionar um *print* da configuração de parcelamento?

**Comment by MarcosLealDev** [comment]
Olá Valdeir,

A configuração da versão anterior dizia que o parcelamento sem juros deveria ser 2.
Nesta versão, a documentação diz que pode ser 1.

Aqui está o print:
![PagSeguro_Parcelamento](https://user-images.githubusercontent.com/14096346/127167120-e9f6cc17-a683-4ada-8fb4-429c9d94609e.jpg)

**Comment by MarcosLealDev** [comment]
Modificando o "Parcelas sem juros" para 2, o pagamento via cartão de crédito funciona sem problemas.

A documentação precisa ser atualizada.
