### ISSUE TITLE
remover opçao de pagamento

### ISSUE THREAD

**Issue by lllWinchesterlll** [opencart-extension/PagSeguro-Checkout-Transparente#59]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Por favor, utilize nosso [canal de atendimento](https://valdeirpsr.atlassian.net/servicedesk/customer/portal/3) ou envie um e-mail para [contato@valdeir.dev](mailto:contato@valdeir.dev)

Obrigado!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
gostaria de remover a opçao   "Pagar ao retirar na loja" que aparece no final do checkuot, é possivel fazer isso ?

**Comment by valdeir2000** [comment]
Olá!

A opção "Pagar ao retirar na loja" é um módulo nativo do OpenCart. Não tem relação com a extensão do PagSeguro.
Você pode desabilitar o módulo acessando o painel administrativo > menu Extensões > Extensões > "Pagar ao retirar na loja"
