### ISSUE TITLE
Erro na página Pagamento após nova instalação

### ISSUE THREAD

**Issue by vynnus** [opencart-extension/PagSeguro-Checkout-Transparente#6]
Valdeir,

o upload e instalação da extensão é feita corretamente.
Mas ao acessar a página Pagamentos para configurar o módulo é retornado o seguinte erro:

**"A página que você está procurando não pode ser encontrada! Entre em contato com o administrador da loja caso o problema persistir."**

E não mais é permitido acessar nenhuma outra forma de pagamento.

**Comment by valdeir2000** [comment]
Qual a versão de sua loja?

**Comment by vynnus** [comment]
2.0.1.1
eu também não consigo finalizar o pedido através do seu site

**Comment by valdeir2000** [comment]
Tenta realizar o download através do link https://mega.nz/#!skdWBTgJ!aIdHTog6glC3miffgWCXF3VZK5PQTqGSQjTJSA5vVqg, pois essa versão do GitHub é somente para OpenCart 2.3.x
