### ISSUE TITLE
PagSeguroDirectPayment is not defined

### ISSUE THREAD

**Issue by luismareze** [opencart-extension/PagSeguro-Checkout-Transparente#8]
Instalei a ultima versao do modulo e eu estou tendo este problema.

"PagSeguroDirectPayment is not defined" no console

Alguem pode ajudar?

**Comment by valdeir2000** [comment]
Em caso de produção:
Acesse o arquivo *catalog/view/theme/*/template/common/header.tpl* > Antes de *</head>* adicione o código abaixo `https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js`

Em caso de teste:
Acesse o arquivo *catalog/view/theme/*/template/common/header.tpl* > Antes de *</head>* adicione o código abaixo `https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js`

**Comment by johnnyboy1988** [comment]
Quando tento carregar o  <script src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"><script>
    antes do </head> o restante da pagina não é apresentado no navegador( se inpeciono a pagina tem as tags html, porem não ficam visíveis..)

Quando carrego o script no final da pagina, a pagina carrega normalmente, porem ocorre o erro mencionado pelo luismareza, "PagSeguroDirectPayment is not defined" no console

**Comment by valdeir2000** [comment]
> Quando tento carregar o <script src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"><script>
> antes do o restante da pagina não é apresentado no navegador( se inpeciono a pagina tem as tags html, porem não ficam visíveis..)
> 
> Quando carrego o script no final da pagina, a pagina carrega normalmente, porem ocorre o erro mencionado pelo luismareza, "PagSeguroDirectPayment is not defined" no console

https://github.com/opencart-extension/PagSeguro-Checkout-Transparente/wiki/%5BComo-Corrigir%5D-Erro-ao-carregar-javascript.
